### ISSUE TITLE
Adding a date picker

### ISSUE THREAD

**Issue by SolomonBier** [AdamBCo/PeekInspiredTimePicker#1]
This is awesome ! Is it possible to add a date picker as well? I see you are calculating NSDate\* today from a seconds conversion so not sure how adding a different day would complicate things (I think it should be the same)

**Comment by AdamBCo** [comment]
Hey SolomonBier,

Thanks for the kind words.

The PeekInspiredTimePicker is suppose to resemble an identical version of the time picker found in the Peek Calendar Application at the moment. In the near future I hope to incorporate a date picker, but I might start a separate project for that. 

If you have any other suggestion for the project, please let me know. Also please feel free to make a pull request as well. I always welcome the opportunity to collaborate with others.

Thank again,
- Adam
