### ISSUE TITLE
Animation of minute/hourLabel when time is clicked is not working properly

### ISSUE THREAD

**Issue by Abhijay** [AdamBCo/PeekInspiredTimePicker#2]
Once it animates to green, it doesn't animate back to the original color, instead it leaves as white. Is this discontinued or have there been improvements?

**Comment by AdamBCo** [comment]
Hey Abhija,

Could you please explain the issue in a little more detail?

From what I can see, that animation does go back to its original background color upon completion.

Do you have a screenshot of the white background color you are referring to?

Thanks for the help,
- Adam

**Comment by Abhijay** [comment]
I closed this earlier today after realizing an error I had made on my own end. Thanks for the follow-up.

**Comment by Abhijay** [comment]
For reference sake, I hadn't realized the Minute Label and Hour Label had clear backgrounds and they relied on the view controller's bgdcolor. When I went to customize the color I modified the labels' background colors. Doing so caused the animations to not run properly. I'm not too sure why the animations don't work without a clear background, but using a clear background color isn't an issue.
