### ISSUE TITLE
Having the Dragged Label automatically update label while panning. 

### ISSUE THREAD

**Issue by Abhijay** [AdamBCo/PeekInspiredTimePicker#3]
Hey, in the native Peek app, the text on the draggedLabel automatically updates to whatever hour/minute it is currently hovering over. Have you experimented with making this possible?

**Comment by AdamBCo** [comment]
I noticed that as well, so I plan on making the fix in the near feature. If you'd like to make a pull request, I welcome the chance to collaborate. Please let me know if you find anything else. Thanks for the help.
